name: Deployment super app

on:
  push:
    branches:
        - main
  workflow_dispatch:

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build application
        run: |
          echo 'Run commands to build an application'
