name: Deployment super app

env:
  APP_VERSION: 1.0.0
  IMAGE_NAME: vilant/acmeapp

on:
  push:
    branches:
        - main
  workflow_dispatch:

jobs:
  build-and-deploy-app:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker
        uses: docker/build-push-action@v6
        with:
          push: true
          build-args: APP_VERSION=${{ env.APP_VERSION }}
          tags: "${{ env.IMAGE_NAME }}:${{ env.APP_VERSION }}"
