name: Deployment super app

env:
  APP_NAME: acme-super-app
  APP_VERSION: 1.0.0
  IMAGE_NAME: vilant/acmeapp
  resourceGroupName: acmeapp-rg

on:
  push:
    branches:
        - main
  workflow_dispatch:

jobs:
  build-and-deploy-app:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker
        uses: docker/build-push-action@v6
        with:
          push: true
          build-args: APP_VERSION=${{ env.APP_VERSION }}
          tags: "${{ env.IMAGE_NAME }}:${{ env.APP_VERSION }}"

      - name: Login to Azure account
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          allow-no-subscriptions: true

      - name: Deploy azure web app
        uses: azure/bicep-deploy@v2
        with:
          type: deployment
          operation: create
          name: Deployment-web-app-${{ env.APP_VERSION }}
          template-file: ./bicep/main.bicep
          scope: resourceGroup
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resource-group-name: ${{ env.resourceGroupName }}
          parameters: '{"appName": "${{ env.APP_NAME }}", "image": "${{ env.IMAGE_NAME }}", "imageTag": "${{ env.APP_VERSION }}"}'
